### ISSUE TITLE
error on cache cleanup

### ISSUE THREAD

**Issue by timblechmann** [frerich/clcache#76] opened 2016-04-18 07:38 UTC
after guarding the stats cache in my personal fork of clcache, i'm getting this error when the compiler cache is cleaned:

```
Traceback (most recent call last):
  File "clcache.py", line 1322, in <module>
  File "clcache.py", line 1224, in main
  File "clcache.py", line 1265, in processCompileRequest
  File "clcache.py", line 1316, in processNoDirect
  File "clcache.py", line 1071, in addObjectToCache
  File "clcache.py", line 176, in clean
WindowsError: [Error 3] The system cannot find the path specified: u'D:\\clcache\\objects\\00\\00e10ae9ecf9db5b0fea0c55fa252e67\\object'
```

**Comment by timblechmann** [comment] 2016-04-18 08:13
seems that `os.stat(fn)` might throw

**Comment by frerich** [comment] 2016-04-19 09:16
It seems plausible to have `os.stat` throw (for a lot of reasons), e.g. if the given file does not exist -- which appears to be the case for you. The code in the `clean` method however reads:

```python
    objects = [os.path.join(root, "object")
               for root, folder, files in os.walk(self.objectsDir)
               if "object" in files]

    objectInfos = [(os.stat(fn), fn) for fn in objects]

I.e. it first recursively enumerates all the files and then calls `os.stat` on them. This could of course throw in case some other process tampers with the cache directory - but I would expect that a separate `clcache` process makes use of the lock file to avoid this.

For what it's worth, on the mainline tree of `clcache`, the entire body of `clean` is guarded by a lock. I seem to recall that in your version, you moved that lock out of the method - is that still the case? If so, maybe something went wrong with that?

**Comment by frerich** [comment] 2016-05-15 19:32
@timblechmann it would be great if you could check whether you can still reproduce this issue, now that PR #77 was merged (which overhauled the locking discipline of clcache). Alas, I was never able to reproduce the problem myself, so I couldn't tell.

**Comment by timblechmann** [comment] 2016-05-15 19:51
will try on our buildservers next week. though there is one thing which is still a bit fishy: the cache lock has a default timeout of 10 seconds. now the caches are cleared while holding the lock. on our buildservers we use several hundred GB of caches, no chance that the cleanup will work within that time. maybe we should also increase the default timeout (principle of least surprise)? with timeout of 100 seconds i haven't seen any issues so far.

**Comment by frerich** [comment] 2016-05-15 20:10
Raising the timeout probably won't hurt, but I believe this is a good opportunity to see whether we can just make clearing the cache faster in the first place. To do so, we would need to know which part of the process is slow exactly.

Can you maybe augment the [`ObjectCache.clean`](../blob/master/clcache.py#L150) method with some trace stements (e.g. by inserting calls to the `printTraceStatement` function) to see how the time is spent? Is it enumerating all the objects in the cache which is slow? Or rather getting their access time? Or maybe the actual process of deleting objects via `rmtree`?

**Comment by webmaster128** [comment] 2016-05-15 23:30
One additional thought: would it help to be able to trigger the cleaning manually (e.g. when system is idle) to minimize the likelihood that cleaning is done during a build?

We don't have this kind of issues due to small cache sizes.

**Comment by frerich** [comment] 2016-05-22 14:57
@timblechmann ping? :-) Just wondering whether you maybe got around to tracing down which part of cleaning the cache was slow for you exactly.

**Comment by timblechmann** [comment] 2016-06-02 09:36
@frerich not yet .. i have a couple of patches, which i first want to integrate before running this on our production servers. i also ended up having a few patches to guard the cleanup with some exception handling to avoid build failures in case of filesystem exceptions ... might be able to devote a bit of time into this over the next days, though ...

**Comment by frerich** [comment] 2016-06-24 12:54
@timblechmann How about we discuss potential improvements to the performance of cleaning the cache in a separate ticket (feel free to open one if you have new findings)? It appears that #77 fixed the original issue by getting the locking right, so I'm tempted to close this ticket.

**Comment by frerich** [comment] 2016-08-25 22:26
Closing it, no activity in two months. For ideas on how to improve performance of cleaning the cache, a separate ticket could be opened.

**Closed by frerich** 2016-08-25 22:26 UTC
Labels: bug
