### ISSUE TITLE
Nothing is cached by clcache

### ISSUE THREAD

**Issue by rptxcosmo** [frerich/clcache#29] opened 2015-03-19 17:38 UTC
- Environment :
 - Visual Studio 2013 Express
 - Windows 7 64 pro
 - clcache master and 3.0.1, (tried both)

- Issue :
 - When i build a project, nothing is cached by clcache.

- Statistics :
C:\Users\cosmo>"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\cl.exe" -s
clcache statistics:
  current cache dir        : C:\clcache
  cache size               : 0 bytes
  maximum cache size       : 1048576000 bytes
  cache entries            : 0
  cache hits               : 0
  cache misses             : 0
  called for linking       : 0
  called w/o sources       : 4
  calls w/ multiple sources: 0
  calls w/ PCH:              0
  evicted misses           : 0
  header changed misses    : 0
  source changed misses    : 0

- The clache folder is almost empty :
Only two empty folders and a stats.txt file.
c:\clcache>tree
C:.
├───manifests
└───objects

**Comment by frerich** [comment] 2015-03-20 10:39
Please post the 'cl' commands executed while building your project.

**Comment by rptxcosmo** [comment] 2015-03-20 11:00
- Here a cl command used for the build :

C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\CL.exe /c /I"C:\build\WBuild-Release-bla-nightly\outprog\include" /I"C:\build\WBuild-Release-bla-nightly\outprog\include\libxml" /I"C:\build\WBuild-Release-bla-nightly\outprog\include\libiconv" /I"c:\build\Src-bla-nightly\coeur\Lib" /I"C:\build\WBuild-Release-bla-nightly\coeur\Lib" /I"c:\build\Src-bla-nightly\coeur\App\ConstructeurProjet" /I"C:\build\WBuild-Release-bla-nightly\coeur\App\ConstructeurProjet" /nologo /W3 /WX- /MP /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D BOOST_ALL_NO_LIB /D NDEBUG /D BOOST_SIGNALS_NO_DEPRECATION_WARNING /D _CRT_FAR_MAPPINGS_NO_DEPRECATE /D _CRT_IS_WCTYPE_NO_DEPRECATE /D _CRT_MANAGED_FP_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _CRT_SECURE_NO_DEPRECATE /D _CRT_SECURE_NO_DEPRECATE_GLOBALS /D _CRT_SETERRORMODE_BEEP_SLEEP_NO_DEPRECATE /D _CRT_TIME_FUNCTIONS_NO_DEPRECATE /D _CRT_VCCLRIT_NO_DEPRECATE /D _SCL_SECURE_NO_DEPRECATE /D _CRT_SECURE_NO_WARNINGS /D "CMAKE_INTDIR=\"Release\"" /D _MBCS /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /GR /Fo"ConstructeurProjet.dir\Release\\" /Fd"ConstructeurProjet.dir\Release\vc120.pdb" /Gd /TP /analyze- /errorReport:queue "c:\build\Src-bla-nightly\coeur\App\ConstructeurProjet\ConstructeurProjet.cxx" "c:\build\Src-bla-nightly\coeur\App\ConstructeurProjet\ImporteurTroisAQuatre.cxx"

**Comment by god3** [comment] 2015-03-23 12:55
I'm having same issue: VS2013 Ultimate, Windows 7 x64 Prof, clcache master.
In output from build i see some notes like "Note: including file:  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\limits.h", but clcache folder are empty.

cl command line:
```
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\CL.exe /c /ZI /nologo /W3 /WX- /Od /Oy- /D WIN32 /D _DEBUG /D _LIB /D _USING_V110_SDK71_ /D _UNICODE /D UNICODE /Gm /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Yu"stdafx.h" /Fp"Win32\Debug\uiWindow.pch" /Fo"Win32\Debug\\" /Fd"Win32\Debug\vc120.pdb" /Gd /TP /analyze- /errorReport:prompt vmsAnimatedGIF.cpp vmsDrawHelper.cpp vmsImage.cpp vmsImage_CtxFree.cpp vmsRenderer.cpp vmsUiButtonWindow.cpp vmsUiCheckBoxWindow.cpp vmsUiHLayout.cpp vmsUiLayout.cpp vmsUiLinkWindow.cpp vmsUiSpacerWindow.cpp vmsUiStaticImageWindow.cpp vmsUiStaticTextWindow.cpp vmsUiStaticTextWindow2.cpp vmsUiStripWindow.cpp vmsUiVLayout.cpp vmsUiWindow.cpp vmsUiWindowEx.cpp vmsUiWindowsHoster.cpp vmsUiWordWrapTextWindow.cpp
```

**Comment by jdonald** [comment] 2015-10-24 21:15
> called w/o sources : 4 (@rptxcosmo)

>  called w/o sources       : 39 (@god3)

I was hitting a similar failure signature earlier, and the root cause turned out to be the parsing error in #31.

Your cause for "called w/o sources" might be something else though. For me the quickest way to diagnose is to turn on the CLCACHE_LOG variable, then you'll see debug info on how clcache parses the separate arguments, and whether or not cl.exe was actually called "w/o sources".

However, even once this is resolved, @god3 you have another issue :

> calls w/ PCH             : 21

> C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\CL.exe /c /ZI ...

You cannot use clcache with /Zi or /ZI. You'll have to turn off debug symbols, use /Z7, or implement #30 :)

**Comment by frerich** [comment] 2016-01-24 00:15
Closing this - my understanding is that the original issue is the same as in #31 (which was fixed). That aside, 'Nothing is cached' is unfortunately a little too imprecise a description for a ticket. Please don't hesitate to open new issue tickets (provided they don't duplicate existing ones) if there are more specific scenarios causing problems. Thanks!

**Closed by frerich** 2016-01-24 00:15 UTC
